export const GET_SUCCESS_EVENTS = 'GET_SUCCESS_EVENTS'
export const GET_FAILURE_EVENTS = 'GET_FAILURE_EVENTS'

export const GET_SUCCESS_EVENTID = 'GET_SUCCESS_EVENTID'
export const GET_FAILURE_EVENTID = 'GET_FAILURE_EVENTID'